"""Map session-file metadata to classifier labels and participant IDs.

Filename convention written by `capture.session_orchestrator`:
    <participant_id>_<label>_<unix_ts>_events.json

`label` is one of:
    human
    bot_raw, bot_smooth, bot_humanised_low, bot_humanised_med, bot_humanised_high
    sm_native_raw, sm_native_smooth, sm_native_humanised_med, sm_native_humanised_high
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# Treat anything that wasn't generated by the participant's hand as the
# positive (aimbot) class for binary classification.
HUMAN_LABELS = {"human"}
BOT_LABELS = {
    "bot_raw", "bot_smooth",
    "bot_humanised_low", "bot_humanised_med", "bot_humanised_high",
    "sm_native_raw", "sm_native_smooth",
    "sm_native_humanised_med", "sm_native_humanised_high",
}
ALL_LABELS = HUMAN_LABELS | BOT_LABELS

# <pid>_<label>_<unix_ts>_events.json — label may itself contain underscores.
_FNAME_RE = re.compile(
    r"^(?P<pid>[A-Za-z0-9]+)_(?P<label>[A-Za-z0-9_]+)_(?P<ts>\d{9,11})_events\.json$"
)


@dataclass(frozen=True)
class SessionMeta:
    path: Path
    participant_id: str
    label: str
    timestamp: int

    @property
    def is_human(self) -> bool:
        return self.label in HUMAN_LABELS

    @property
    def binary_target(self) -> int:
        """0 = human, 1 = aimbot of any kind."""
        return 0 if self.is_human else 1


def parse_session_filename(path: Path) -> SessionMeta | None:
    """Return SessionMeta for a recognised events file, else None.

    Unknown labels are rejected rather than silently mapped — a typo in a
    participant's label would otherwise poison the training set.
    """
    m = _FNAME_RE.match(path.name)
    if m is None:
        return None
    label = m.group("label")
    if label not in ALL_LABELS:
        return None
    return SessionMeta(
        path=path,
        participant_id=m.group("pid"),
        label=label,
        timestamp=int(m.group("ts")),
    )


def discover_sessions(root: Path, recursive: bool = True,
                     exclude_dirs: tuple[str, ...] = ("OLD", "Questionnaire", "Deception questions"),
                     allowed_labels: set[str] | None = None,
                     ) -> list[SessionMeta]:
    """List every recognised events.json under `root`.

    Recursive by default so the per-participant subdir layout (sessions/P01/…)
    works out of the box. Directories whose name appears in `exclude_dirs` are
    pruned entirely — used to skip the pilot/test data in `sessions/OLD/` and
    questionnaire JSON folders.

    If `allowed_labels` is provided, only sessions whose parsed label is in
    that set are kept (used to restrict to {human, sm_native_smooth,
    sm_native_humanised_high} for the final classifier).
    """
    metas: list[SessionMeta] = []
    pattern = "**/*_events.json" if recursive else "*_events.json"
    excluded = set(exclude_dirs)
    for p in sorted(root.glob(pattern)):
        if any(part in excluded for part in p.relative_to(root).parts[:-1]):
            continue
        meta = parse_session_filename(p)
        if meta is None:
            continue
        if allowed_labels is not None and meta.label not in allowed_labels:
            continue
        metas.append(meta)
    return metas


# ---------------------------------------------------------------------------
# Task / label-mapping configuration
# ---------------------------------------------------------------------------

# The recorded final-study conditions. `_med` was on the planning sheet but
# `_high` is what actually got recorded — confirm with `discover_sessions` if
# this assumption ever needs revisiting.
FINAL_STUDY_LABELS: tuple[str, ...] = (
    "human",
    "sm_native_smooth",
    "sm_native_humanised_high",
)

MULTICLASS_LABEL_TO_ID: dict[str, int] = {
    "human": 0,
    "sm_native_smooth": 1,
    "sm_native_humanised_high": 2,
}

TASK_LABELS: dict[str, tuple[str, ...]] = {
    "binary_all": FINAL_STUDY_LABELS,
    "binary_smooth": ("human", "sm_native_smooth"),
    "binary_humanised": ("human", "sm_native_humanised_high"),
    "multiclass": FINAL_STUDY_LABELS,
}


def label_mapping(task: str) -> dict[str, int]:
    """Return {label_string: class_index} for the requested task.

    Supported task names:
      - binary / binary_all: human vs all recognised aimbot labels
      - binary_smooth: human vs sm_native_smooth
      - binary_humanised: human vs sm_native_humanised_high
      - multiclass: human / sm_native_smooth / sm_native_humanised_high
    """
    if task in {"binary", "binary_all"}:
        m = {"human": 0}
        m.update({lbl: 1 for lbl in BOT_LABELS})
        return m
    if task == "binary_smooth":
        return {"human": 0, "sm_native_smooth": 1}
    if task == "binary_humanised":
        return {"human": 0, "sm_native_humanised_high": 1}
    if task == "multiclass":
        return dict(MULTICLASS_LABEL_TO_ID)
    raise ValueError(
        f"Unknown task: {task!r}. Expected one of: "
        "binary, binary_all, binary_smooth, binary_humanised, multiclass."
    )


def labels_for_task(task: str) -> tuple[str, ...]:
    """Condition labels included in a task."""
    if task == "binary":
        task = "binary_all"
    if task not in TASK_LABELS:
        # Validate through label_mapping for a clearer error.
        label_mapping(task)
    return TASK_LABELS[task]
