"""Map session-file metadata to classifier labels and participant IDs.

Filename convention written by `capture.session_orchestrator`:
    <participant_id>_<label>_<unix_ts>_events.json

`label` is one of:
    human
    bot_raw, bot_smooth, bot_humanised_low, bot_humanised_med, bot_humanised_high
    sm_native_raw, sm_native_smooth, sm_native_humanised_med, sm_native_humanised_high
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# Treat anything that wasn't generated by the participant's hand as the
# positive (aimbot) class for binary classification.
HUMAN_LABELS = {"human"}
BOT_LABELS = {
    "bot_raw", "bot_smooth",
    "bot_humanised_low", "bot_humanised_med", "bot_humanised_high",
    "sm_native_raw", "sm_native_smooth",
    "sm_native_humanised_med", "sm_native_humanised_high",
}
ALL_LABELS = HUMAN_LABELS | BOT_LABELS

# <pid>_<label>_<unix_ts>_events.json — label may itself contain underscores.
_FNAME_RE = re.compile(
    r"^(?P<pid>[A-Za-z0-9]+)_(?P<label>[A-Za-z0-9_]+)_(?P<ts>\d{9,11})_events\.json$"
)


@dataclass(frozen=True)
class SessionMeta:
    path: Path
    participant_id: str
    label: str
    timestamp: int

    @property
    def is_human(self) -> bool:
        return self.label in HUMAN_LABELS

    @property
    def binary_target(self) -> int:
        """0 = human, 1 = aimbot of any kind."""
        return 0 if self.is_human else 1


def parse_session_filename(path: Path) -> SessionMeta | None:
    """Return SessionMeta for a recognised events file, else None.

    Unknown labels are rejected rather than silently mapped — a typo in a
    participant's label would otherwise poison the training set.
    """
    m = _FNAME_RE.match(path.name)
    if m is None:
        return None
    label = m.group("label")
    if label not in ALL_LABELS:
        return None
    return SessionMeta(
        path=path,
        participant_id=m.group("pid"),
        label=label,
        timestamp=int(m.group("ts")),
    )


def discover_sessions(root: Path) -> list[SessionMeta]:
    """List every recognised events.json in `root` (non-recursive)."""
    metas = []
    for p in sorted(root.glob("*_events.json")):
        meta = parse_session_filename(p)
        if meta is not None:
            metas.append(meta)
    return metas
